version: 2.0

defaults: &defaults
  docker: # use the docker executor type; machine and macos executors are also supported
    - image: circleci/node:10 # the primary container, where your job's commands are run

jobs:
  build:
    <<: *defaults
    steps:
      - checkout # check out the code in the project directory
      - restore_cache: # Restores a previously saved cache based on a key (or keys)
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-cache-{{ checksum "package.json" }}

      - run: # used for invoking all command-line programs
          name: Install Dependencies
          command: yarn # --frozen-lockfile

      - save_cache: # Generates and stores a cache of a file or directory of files
          name: Save Yarn Package Cache
          key: yarn-packages-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ~/.cache/yarn
      #          paths:
      #            - ~/.cache/yarn
      - run: yarn lint --max-warnings 1
      - run: yarn build
      - run: yarn semantic-release
